spring:
  datasource:
    url: jdbc:h2:mem:ComputerShop;INIT=CREATE SCHEMA IF NOT EXISTS "COMPUTERSHOP"
    driver-class-name: org.h2.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

server:
  port: 8087
