create table computer_shop.cart (id_cart bigint not null, city varchar(255), content varchar(255), country varchar(255), created_at date, email varchar(255), first_name varchar(255), last_name varchar(255), line1 varchar(255), line2 varchar(255), middle_name varchar(255), mobile varchar(255), province varchar(255), session_id varchar(255), status varchar(255), token varchar(255), updated_at date, user_id_user bigint, primary key (id_cart)) engine=InnoDB;
create table computer_shop.cart_item (id_cart_item bigint not null, active bit not null, content varchar(255), created_at date, discount FLOAT default 0, price FLOAT default 0, quantity FLOAT default 0, sku varchar(255), updated_at date, cart_id_cart bigint, product_id_product bigint, primary key (id_cart_item)) engine=InnoDB;
create table computer_shop.category (id_category bigint not null, content varchar(255), meta_title varchar(255), slug varchar(255), title varchar(255), primary key (id_category)) engine=InnoDB;
create table computer_shop.order (id_order bigint not null, city varchar(255), content integer, country varchar(255), created_at date, discount FLOAT default 0, email varchar(255), first_name varchar(255), grand_total FLOAT default 0, item_discount FLOAT default 0, last_name varchar(255), line1 varchar(255), line2 varchar(255), middle_name varchar(255), mobile varchar(255), promo varchar(255), province varchar(255), session_id varchar(255), shipping FLOAT default 0, status varchar(255), sub_total FLOAT default 0, tax FLOAT default 0, token varchar(255), total FLOAT default 0, updated_at date, user_id_user bigint, primary key (id_order)) engine=InnoDB;
create table computer_shop.order_item (id_order_item bigint not null, content varchar(255), created_at date, discount FLOAT default 0, price FLOAT default 0, quantity SMALLINT default 0, sku varchar(255), updated_at date, order_id_order bigint, product_id_product bigint, primary key (id_order_item)) engine=InnoDB;
create table computer_shop.product (id_product bigint not null, content varchar(255), created_at date, discount FLOAT default 0, meta_title varchar(255), price FLOAT default 0, published_at date, quantity integer not null, sku varchar(255), summary varchar(255), title varchar(255), updated_at date, user_id_user bigint, primary key (id_product)) engine=InnoDB;
create table computer_shop.product_category (product_category bigint not null, category_id_category bigint, product_id_product bigint, primary key (product_category)) engine=InnoDB;
create table computer_shop.product_meta (product_meta bigint not null, content varchar(255), keyy varchar(255), product_id_product bigint, primary key (product_meta)) engine=InnoDB;
create table computer_shop.product_review (id_product_review bigint not null, content varchar(255), created_at date, published bit not null, published_at date, rating integer not null, title varchar(255), product_id_product bigint, primary key (id_product_review)) engine=InnoDB;
create table computer_shop.transaction (id_transaction bigint not null, code varchar(255), content varchar(255), created_at date, mode varchar(255), status varchar(255), type varchar(255), updated_at date, order_id_order bigint, user_id_user bigint, primary key (id_transaction)) engine=InnoDB;
create table computer_shop.user (id_user bigint not null, email varchar(255), first_name varchar(255), is_admin bit not null, is_vendor bit not null, last_login date, last_name varchar(255), middle_name varchar(255), mobile varchar(255), password varchar(255), registered date, primary key (id_user)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
alter table computer_shop.cart add constraint FKi2tku0noerc66q983c6wa6dex foreign key (user_id_user) references computer_shop.user (id_user);
alter table computer_shop.cart_item add constraint FK59d6nlh0rwtd8faofc1aljfip foreign key (cart_id_cart) references computer_shop.cart (id_cart);
alter table computer_shop.cart_item add constraint FKcj377vme82401r3n2dapdgxcs foreign key (product_id_product) references computer_shop.product (id_product);
alter table computer_shop.order add constraint FKij73ggncsbmk3647kxfuk830j foreign key (user_id_user) references computer_shop.user (id_user);
alter table computer_shop.order_item add constraint FKswesmr1nb49isa1pe1kfxeshv foreign key (order_id_order) references computer_shop.order (id_order);
alter table computer_shop.order_item add constraint FKb0eiq6q112nds4ry62h4pgwrn foreign key (product_id_product) references computer_shop.product (id_product);
alter table computer_shop.product add constraint FKr6g8p4qbe9fg46pgrqyjpd2je foreign key (user_id_user) references computer_shop.user (id_user);
alter table computer_shop.product_category add constraint FKdsyja6py7bwrsf72y64gmyum1 foreign key (category_id_category) references computer_shop.category (id_category);
alter table computer_shop.product_category add constraint FKiqp3ssrm74fcu2tx83m7tu4i9 foreign key (product_id_product) references computer_shop.product (id_product);
alter table computer_shop.product_meta add constraint FKb0ogmp8u4w27h8asdvvqjcybq foreign key (product_id_product) references computer_shop.product (id_product);
alter table computer_shop.product_review add constraint FKcmqrvd82alqhak0iu7wuu6dib foreign key (product_id_product) references computer_shop.product (id_product);
alter table computer_shop.transaction add constraint FKqmtyblaxx5mh2l7e8y3bneq5d foreign key (order_id_order) references computer_shop.order (id_order);
alter table computer_shop.transaction add constraint FKfw0eud60ok9my47w89ficshme foreign key (user_id_user) references computer_shop.user (id_user);
